const responses = [
    "As I see it, yes",
    "Ask again later, I'm sleeping",
    "Better not tell you now",
    "Cannot predict now",
    "Concentrate and ask again",
    "Don’t count on it",
    "It is certain",
    "It is decidedly so",
    "Most likely",
    "My reply is no",
    "My sources say no",
    "Outlook good",
    "Outlook not so good",
    "Reply hazy, try again",
    "Signs point to yes",
    "Very doubtful",
    "Without a doubt",
    "Yes, definitely",
    "You may rely on it",
    "Absolutely not",
    "Forget about it",
    "In your dreams",
    "Not a chance",
    "Not in this lifetime",
    "I don't think so",
    "Fat chance",
    "When pigs fly",
    "You wish",
    "In a parallel universe",
    "Maybe in the afterlife",
    "When you least expect it",
    "When I'm feeling generous",
    "On the 12th of Never",
    "Once in a blue moon",
    "When bananas dance",
    "When cows jump over the moon",
    "When pigs learn to fly",
    "The day you get a date",
    "Maybe when unicorns exist",
    "After dinner and a movie",
    "When you clean your room",
    "When frogs grow feathers",
    "On the next blue moon",
    "When you win the lottery",
    "When you ace that exam",
    "After you eat your veggies",
    "Maybe after your nap",
    "When you become president",
    "On your 100th birthday",
    "Not until the sun explodes",
    "Yeah right, bucko",
    "In the distant future",
    "Never say never",
    "Anything's possible",
    "Miracles can happen",
    "With hard work and dedication",
    "You'll have to convince me",
    "It's a definite maybe",
    "I'd have to think about it",
    "Ask me on a better day",
    "It's unclear at this time",
    "I can't say for certain",
    "I need more information",
    "I don't have enough data",
    "Results inconclusive",
    "Check back in a bit",
    "I haven't decided yet",
    "Your guess is as good as mine",
    "No idea, pal",
    "I couldn't possibly say",
    "I'm drawing a blank",
    "I'm going to need more time",
    "Good question - no idea",
    "Let me get back to you",
    "I forgot to check the forecast",
    "My crystal ball is foggy",
    "My WiFi is spotty today",
    "My fortune telling is offline",
    "My tarot cards are shuffling",
    "Let me grab my magic 8 ball",
    "My psychic powers failed me",
    "Come back when Mercury is out of retrograde",
    "The spirits aren't talking to me today",
    "I'm still waiting on my astrology reading",
    "My tea leaves say:  ̄\\_(ツ)_/ ̄",
    "The Universe didn't send me a signal yet",
    "Sorry, fresh out of predictions over here",
    "My horoscope didn't cover this scenario",
    "The stars say:  ̄\\_(ツ)_/ ̄",
    "Beats me, I'm not a mind reader",
    "I left my crystal ball at home today",
    "Let me check with my cat and get back to you"
];

export async function eightBallresponse() {
    const response = responses[Math.floor(Math.random() * responses.length)];
    return response;
}